
name: CICD

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Dev" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Terraform plan
        run: terraform plan -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" -var="aws_secret_key=${{ secrets.AWS_SECRET_KEY }}" -out plan.tfout   
      
      - name: Terraform Apply
        run: terraform apply -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" -var="aws_secret_key=${{ secrets.AWS_SECRET_KEY }}"  "plan.tfout"  
