
name: CICD

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Dev" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "init message"

